{"name": "Ошибка при создании одинаковых курьеров", "status": "passed", "description": "Проверяем ошибку при создании курьера с уже существующими данными", "steps": [{"name": "Отправляем запрос на создание пользователя", "status": "passed", "start": 1711903332310, "stop": 1711903332723}, {"name": "Отправляем запрос для пользователя с уже существующими данными", "status": "passed", "start": 1711903332723, "stop": 1711903333098}, {"name": "Пользователя невозможно создать с уже существущими данными.Код ответа - 409, тело ответа - \"Этот логин уже используется. Попробуйте другой.\"", "status": "passed", "start": 1711903333098, "stop": 1711903333098}], "start": 1711903332310, "stop": 1711903333100, "uuid": "b9170c36-6a64-4050-9572-d2b8b9ac5090", "historyId": "50ebec093ab23e1f5d9397faba9a286a", "testCaseId": "50ebec093ab23e1f5d9397faba9a286a", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_same_courier", "labels": [{"name": "suite", "value": "Создание курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "System-Product"}, {"name": "thread", "value": "30350-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}